changelog:
  categories:
    - title: New Features
      labels:
        - enhancement
        - feat
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Refactor
      labels:
        - refactor
    - title: Chores
      labels:
        - chore
        - dependencies
        - ci
        - docs
